# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replic.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'replic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creplic.proto\x12\nreplicator\"=\n\x0cWriteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x11\n\ttestError\x18\x03 \x01(\t\"1\n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1b\n\x0cQueryRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"-\n\rQueryResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"E\n\x08LogEntry\x12\r\n\x05\x65poch\x18\x01 \x01(\x03\x12\x0e\n\x06offset\x18\x02 \x01(\x03\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\"j\n\x14\x41ppendEntriesRequest\x12\x14\n\x0cleader_epoch\x18\x01 \x01(\x03\x12\x17\n\x0fprev_log_offset\x18\x02 \x01(\x03\x12#\n\x05\x65ntry\x18\x03 \x01(\x0b\x32\x14.replicator.LogEntry\"W\n\x15\x41ppendEntriesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0e\x63urrent_offset\x18\x02 \x01(\x03\x12\x15\n\rcurrent_epoch\x18\x03 \x01(\x03\"\x1f\n\rCommitRequest\x12\x0e\n\x06offset\x18\x01 \x01(\x03\"!\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x8b\x01\n\rClientService\x12<\n\x05Write\x12\x18.replicator.WriteRequest\x1a\x19.replicator.WriteResponse\x12<\n\x05Query\x12\x18.replicator.QueryRequest\x1a\x19.replicator.QueryResponse2\xb0\x01\n\x12ReplicationService\x12T\n\rAppendEntries\x12 .replicator.AppendEntriesRequest\x1a!.replicator.AppendEntriesResponse\x12\x44\n\x0b\x43ommitEntry\x12\x19.replicator.CommitRequest\x1a\x1a.replicator.CommitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITEREQUEST']._serialized_start=28
  _globals['_WRITEREQUEST']._serialized_end=89
  _globals['_WRITERESPONSE']._serialized_start=91
  _globals['_WRITERESPONSE']._serialized_end=140
  _globals['_QUERYREQUEST']._serialized_start=142
  _globals['_QUERYREQUEST']._serialized_end=169
  _globals['_QUERYRESPONSE']._serialized_start=171
  _globals['_QUERYRESPONSE']._serialized_end=216
  _globals['_LOGENTRY']._serialized_start=218
  _globals['_LOGENTRY']._serialized_end=287
  _globals['_APPENDENTRIESREQUEST']._serialized_start=289
  _globals['_APPENDENTRIESREQUEST']._serialized_end=395
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=397
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=484
  _globals['_COMMITREQUEST']._serialized_start=486
  _globals['_COMMITREQUEST']._serialized_end=517
  _globals['_COMMITRESPONSE']._serialized_start=519
  _globals['_COMMITRESPONSE']._serialized_end=552
  _globals['_CLIENTSERVICE']._serialized_start=555
  _globals['_CLIENTSERVICE']._serialized_end=694
  _globals['_REPLICATIONSERVICE']._serialized_start=697
  _globals['_REPLICATIONSERVICE']._serialized_end=873
# @@protoc_insertion_point(module_scope)
